- name: manage state of windows services
  hosts: mixed_web_servers
  connection: local
  gather_facts: True

  tasks:
    
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    
    
