- name: manage state of windows services
  hosts: mixed_web_servers
  connection: local
  gather_facts: True

  tasks:
    
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print os type
      ansible.builtin.debug:
        var: ansible_distribution    
    
    - name: set windows specific value for mode var
      set_fact:
        mode: auto
        service: Web-Server
      when: 'mode_survey == yes and "windows" in ansible_distribution' 

    - name: set windows specific value for mode var
      set_fact:
        mode: manual
        service: Web-Server
      when: 'mode_survey == no and "windows" in ansible_distribution'

    - name: set windows specific value for mode var
      set_fact:
        service: httpd
      when: 'ansible_distribution contains "red"'    

    - name: Set service startup mode and current state
      win_service:
        name: "{{ service }}"
        start_mode: "{{ mode }}"
        state: "{{ service_state }}"
      when: '"windows" in ansible_distribution'   

    - name: Set service startup mode and current state
      service:
        name: "{{ service }}"
        state: "{{ service_state }}"
        enabled: "{{ mode_survey }}" 
      when: '"red" in ansible_distribution'     
