- name: manage state of windows services
  hosts: mixed_web_servers
  connection: local
  gather_facts: False

  tasks:
    
    - name: RHEL
      include_role:
        name: "roles/services_rhel"
      when:
        - os == rhel

    - name: Windows 
      include_role:
        name: "roles/services_windows"
      when:
        - os == windows
    
    
