- name: manage state of windows services
  hosts: mixed_web_servers
  connection: local
  gather_facts: True

  tasks:
    
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print os type
      ansible.builtin.debug:
        var: ansible_distribution    
    
    - name: set windows specific value for mode var
      set_fact:
        mode: auto
        service: Web-Server
      when: mode_survey == yes and ansible_distribution contains "windows"

    - name: set windows specific value for mode var
      set_fact:
        mode: manual
        service: Web-Server
      when: mode_survey == no and ansible_distribution contains "windows"

    - name: set windows specific value for mode var
      set_fact:
        service: httpd
      when: ansible_distribution contains "red"      

    - name: Set service startup mode and current state
      ansible.windows.win_service:
        name: "{{ service }}"
        start_mode: "{{ mode }}"
        state: "{{ service_state }}"
      when: ansible_distribution contains "windows"   

    - name: Set service startup mode and current state
      service:
        name: "{{ service }}"
        state: "{{ service_state }}"
        enabled: "{{ mode_survey }}" 
      when: ansible_distribution contains "red"     
