- name: manage state of windows services
  hosts: mixed_web_servers
  connection: local
  gather_facts: True

  tasks:
    
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print os type
      ansible.builtin.debug:
        var: ansible_distribution   

    - name: set windows specific value for service
      set_fact:
        service: Web-Server
      when: '"Windows" in ansible_distribution and service_survey == "web service"' 

    - name: set RHEL specific value for service var
      set_fact:
        service: httpd
      when: '"RedHat" in ansible_distribution and service_survey == "web service"'     
    
    - name: set windows specific value for mode var
      set_fact:
        mode: auto
      when: 'mode_survey == "yes" and "Windows" in ansible_distribution' 

    - name: set windows specific value for mode var
      set_fact:
        mode: manual
      when: 'mode_survey == "no" and "Windows" in ansible_distribution'

    - name: Set service startup mode and current state
      win_service:
        name: "{{ service }}"
        start_mode: "{{ mode }}"
        state: "{{ service_state }}"
      when: '"Windows" in ansible_distribution'   

    - name: Set service startup mode and current state
      service:
        name: "{{ service }}"
        state: "{{ service_state }}"
        enabled: "{{ mode_survey }}" 
      when: '"RedHat" in ansible_distribution'     
